import 'dotenv/config'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  await prisma.game.createMany({
    data: [
      {
        homeTeam: 'Flamengo',
        awayTeam: 'Palmeiras',
        oddsHome: 2.1,
        oddsDraw: 3.2,
        oddsAway: 2.8,
        status: 'OPEN',
        startsAt: new Date('2026-04-05T19:00:00Z'),
      },
      {
        homeTeam: 'Real Madrid',
        awayTeam: 'Barcelona',
        oddsHome: 1.9,
        oddsDraw: 3.5,
        oddsAway: 3.0,
        status: 'OPEN',
        startsAt: new Date('2026-04-06T20:00:00Z'),
      },
      {
        homeTeam: 'Manchester City',
        awayTeam: 'Liverpool',
        oddsHome: 2.2,
        oddsDraw: 3.1,
        oddsAway: 2.6,
        status: 'OPEN',
        startsAt: new Date('2026-04-07T18:30:00Z'),
      },
      {
        homeTeam: 'São Paulo',
        awayTeam: 'Corinthians',
        oddsHome: 2.4,
        oddsDraw: 3.0,
        oddsAway: 2.5,
        status: 'OPEN',
        startsAt: new Date('2026-04-08T21:00:00Z'),
      },
      {
        homeTeam: 'Bayern Munich',
        awayTeam: 'Borussia Dortmund',
        oddsHome: 1.7,
        oddsDraw: 3.8,
        oddsAway: 4.2,
        status: 'OPEN',
        startsAt: new Date('2026-04-09T19:30:00Z'),
      },
    ],
    skipDuplicates: true,
  })

  await prisma.casinoGame.deleteMany({})

  await prisma.casinoGame.createMany({
    data: [
      {
        title: 'Gates of Olympus',
        provider: 'Pragmatic Play',
        category: 'SLOTS',
        sections: ['featured', 'popular'],
        badge: 'HOT',
        multiplier: '5000x',
        accent: '#3A86FF',
        gameUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20olympgate&lang=pt&cur=BRL&lobbyUrl=about:blank',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Sweet Bonanza',
        provider: 'Pragmatic Play',
        category: 'SLOTS',
        sections: ['featured', 'popular'],
        badge: 'HOT',
        multiplier: '21100x',
        accent: '#FB5607',
        gameUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20fruitsw&lang=pt&cur=BRL&lobbyUrl=about:blank',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Sugar Rush',
        provider: 'Pragmatic Play',
        category: 'SLOTS',
        sections: ['popular', 'new'],
        badge: 'NOVO',
        multiplier: '5000x',
        accent: '#FF006E',
        gameUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20sugarrush&lang=pt&cur=BRL&lobbyUrl=about:blank',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Starlight Princess',
        provider: 'Pragmatic Play',
        category: 'SLOTS',
        sections: ['popular'],
        badge: null,
        multiplier: '5000x',
        accent: '#8338EC',
        gameUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20starlight&lang=pt&cur=BRL&lobbyUrl=about:blank',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Big Bass Bonanza',
        provider: 'Pragmatic Play',
        category: 'SLOTS',
        sections: ['popular'],
        badge: null,
        multiplier: '2100x',
        accent: '#0077B6',
        gameUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs10bbbonanza&lang=pt&cur=BRL&lobbyUrl=about:blank',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Mahjong Ways',
        provider: 'PG Soft',
        category: 'SLOTS',
        sections: ['popular'],
        badge: null,
        multiplier: '1500x',
        accent: '#E63946',
        gameUrl: 'https://public.pg-demo.com/games/play/?gid=50&lang=pt&currency=BRL',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Fortune Mouse',
        provider: 'PG Soft',
        category: 'SLOTS',
        sections: ['featured', 'new'],
        badge: 'NOVO',
        multiplier: '1000x',
        accent: '#FFD60A',
        gameUrl: 'https://public.pg-demo.com/games/play/?gid=53&lang=pt&currency=BRL',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Wild Bandito',
        provider: 'PG Soft',
        category: 'SLOTS',
        sections: ['popular'],
        badge: null,
        multiplier: '2500x',
        accent: '#FF6B35',
        gameUrl: 'https://public.pg-demo.com/games/play/?gid=92&lang=pt&currency=BRL',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Leprechaun Riches',
        provider: 'PG Soft',
        category: 'SLOTS',
        sections: ['new'],
        badge: 'NOVO',
        multiplier: '2000x',
        accent: '#2DC653',
        gameUrl: 'https://public.pg-demo.com/games/play/?gid=45&lang=pt&currency=BRL',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Candy Superwin',
        provider: 'PG Soft',
        category: 'SLOTS',
        sections: ['new'],
        badge: 'NOVO',
        multiplier: '3000x',
        accent: '#FF85A1',
        gameUrl: 'https://public.pg-demo.com/games/play/?gid=91&lang=pt&currency=BRL',
        imageUrl: null,
        active: true,
      },
      {
        title: '3 Pots of Wishes',
        provider: 'Betsoft',
        category: 'SLOTS',
        sections: ['new'],
        badge: 'NOVO',
        multiplier: '1200x',
        accent: '#7209B7',
        gameUrl: 'https://betsoft.com/play-demo?id=7533',
        imageUrl: null,
        active: true,
      },
      {
        title: 'Dr. Jekyll & Mr. Hyde 2',
        provider: 'Betsoft',
        category: 'SLOTS',
        sections: ['popular'],
        badge: null,
        multiplier: '800x',
        accent: '#4A4E69',
        gameUrl: 'https://betsoft.com/play-demo?id=7508',
        imageUrl: null,
        active: true,
      },
      {
        title: 'The King of Social Media',
        provider: 'Betsoft',
        category: 'SLOTS',
        sections: ['new'],
        badge: 'NOVO',
        multiplier: '1500x',
        accent: '#FF9F1C',
        gameUrl: 'https://betsoft.com/play-demo?id=7298',
        imageUrl: null,
        active: true,
      },
    ],
    skipDuplicates: true,
  })

  await prisma.story.createMany({
    data: [
      {
        title: '1 MILHÃO',
        videoUrl: 'https://igbxyvhkcaynscxmouyw.supabase.co/storage/v1/object/public/story-videos/WhatsApp%20Video%202026-03-25%20at%2023.47.54.mp4',
        order: 1,
      },
      {
        title: 'COTAÇÕES',
        videoUrl: 'https://igbxyvhkcaynscxmouyw.supabase.co/storage/v1/object/public/story-videos/WhatsApp%20Video%202026-03-25%20at%2023.48.03.mp4',
        order: 2,
      },
      {
        title: 'PRÊMIOS',
        videoUrl: 'https://igbxyvhkcaynscxmouyw.supabase.co/storage/v1/object/public/story-videos/WhatsApp%20Video%202026-03-25%20at%2023.48.22.mp4',
        order: 3,
      },
      {
        title: 'CASHBACK',
        videoUrl: 'https://igbxyvhkcaynscxmouyw.supabase.co/storage/v1/object/public/story-videos/WhatsApp%20Video%202026-03-25%20at%2023.48.23.mp4',
        order: 4,
      },
      {
        title: 'GRÁTIS',
        videoUrl: 'https://igbxyvhkcaynscxmouyw.supabase.co/storage/v1/object/public/story-videos/WhatsApp%20Video%202026-03-25%20at%2023.50.15.mp4',
        order: 5,
      },
    ],
    skipDuplicates: true,
  })
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
